import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, relative } from 'node:path'
import process from 'node:process'
import glob from 'tiny-glob'

const srcDir = new URL('../src', import.meta.url).pathname
const featuresDir = `${srcDir}/features/optimized`
const outputFile = `${srcDir}/generated/features.ts`

function escapeString(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, '\\\'').replace(/\n/g, '\\n').replace(/\r/g, '\\r')
}

async function main() {
  const files = await glob('**/*.svg', { cwd: featuresDir })
  const entries: string[] = []

  for (const file of files.sort()) {
    const content = await readFile(`${featuresDir}/${file}`, 'utf-8')
    const key = `./features/optimized/${file}`
    entries.push(`  '${escapeString(key)}': '${escapeString(content.trim())}'`)
  }

  const output = `// Auto-generated by scripts/generate-features.ts
export const identiconFeatures: Record<string, string> = {
${entries.join(',\n')},
}
`

  await mkdir(dirname(outputFile), { recursive: true })
  await writeFile(outputFile, output)
  console.log(`✓ Generated ${relative(process.cwd(), outputFile)} with ${entries.length} SVGs`)
}

main()
